# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: 'imagenet'
data_dir: '/data/imagenet'
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# augmentation
image_resize: 224
hflip: 0.5
color_jitter: 0.4
interpolation: 'bilinear'
crop_pct: 0.875
re_prob: 0.5

# model
model: 'shufflenet_v2_x2_0'
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
ckpt_save_dir: './ckpt'
epoch_size: 300
dataset_sink_mode: True
amp_level: 'O0'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.5
warmup_epochs: 5
decay_epochs: 295

# optimizer
opt: 'momentum'
filter_bias_and_bn: False
momentum: 0.9
weight_decay: 0.00004
loss_scale: 1
use_nesterov: False
