# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 256
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bicubic'
re_prob: 0.25
mixup: 0.2
cutmix: 1.0
cutmix_prob: 1.0
crop_pct: 0.875
color_jitter: 0.4

# model
model: 'convit_tiny'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'
epoch_size: 300
dataset_sink_mode: True
amp_level: 'O2'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
lr: 0.00072
min_lr: 0.000001
warmup_epochs: 5
decay_epochs: 295

# optimizer
opt: 'adamw'
weight_decay: 0.0001
loss_scale: 1024
filter_bias_and_bn: True
use_nesterov: False
