# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True
val_interval: 1

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: "bilinear"
auto_augment: "randaug-m7-mstd0.5"
re_prob: 0.1
mixup: 0.2
cutmix: 1.0
cutmix_prob: 1.0

# model
model: "hrnet_w32"
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 5
ckpt_save_policy: "top_k"
ckpt_save_dir: "./ckpt"
epoch_size: 300
dataset_sink_mode: True
amp_level: "O2"

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
min_lr: 0.00001
lr: 0.001
warmup_epochs: 20
decay_epochs: 280

# optimizer
opt: 'adamw'
weight_decay: 0.05
loss_scale: 1024
filter_bias_and_bn: True
