# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 75
drop_remainder: True
train_split: 'train'

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
color_jitter: 0.4
interpolation: 'bilinear'
crop_pct: 0.875

# model
model: 'mobilenet_v3_small_100'
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
ckpt_save_dir: './ckpt'
epoch_size: 470
dataset_sink_mode: True
amp_level: 'O0'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.77
warmup_epochs: 4
decay_epochs: 466

# optimizer
opt: 'momentum'
filter_bias_and_bn: False
momentum: 0.9
weight_decay: 0.00004
loss_scale: 1024
use_nesterov: False
