# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 32
drop_remainder: True

# augmentation
image_resize: 224
hflip: 0.5
crop_pct: 0.875

# model
model: 'BiTresnet50'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'
epoch_size: 90
dataset_sink_mode: True
amp_level: 'O0'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'multi_step_decay'
lr: 0.06
decay_rate: 0.5
multi_step_decay_milestones: [30, 40, 50, 60, 70, 80, 85]

# optimizer
opt: 'sgd'
filter_bias_and_bn: False
momentum: 0.9
weight_decay: 0.0001
loss_scale: 1024
