# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 32
drop_remainder: True

# augmentation
image_resize: 299
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bilinear'
auto_augment: 'autoaug'
re_prob: 0.25
crop_pct: 0.875

# model
model: 'xception'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'
epoch_size: 200
dataset_sink_mode: True
amp_level: 'O2'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'warmup_cosine_decay'
lr: 0.045
min_lr: 0.0
decay_epochs: 195
warmup_epochs: 5

# optimizer
opt: 'sgd'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.00001
loss_scale: 1024
use_nesterov: False
